### ISSUE TITLE
The badge doesn't work

### ISSUE THREAD

**Issue by FroggyRocky** [akellbl4/spotify-badge#19]
I mentioned that the badge stopped working, I think the issue might be in tsconfig, one I changed tsconfig jsx from preserver to react, it started working. PM #18

**Comment by FroggyRocky** [comment]
![image](https://github.com/user-attachments/assets/02bbc80c-b2c2-432b-acd8-390de10d2217)

**Comment by akellbl4** [comment]
@FroggyRocky, thank you for your contribution, I appreciate it. Apparently, I was following the wrong lead when trying to figure this problem out.

Resolved #18
