### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by SaicharanKandukuri** [akellbl4/spotify-badge#2]
hey there 
I tried deploying your app
but I can get a refresh token it shows `INVALID_CLIENT: Invalid redirect URI`

**Comment by SaicharanKandukuri** [comment]
Hello @akellbl4

**Comment by SaicharanKandukuri** [comment]
nvm i got it

**Comment by barbarbar338** [comment]
> nvm i got it

but how?

**Comment by akellbl4** [comment]
@barbarbar338 the error occurs when you have incorrect redirect URL on app settings in Spotify.

> - Add path to auth page /api/auth. It should looks like this https://spotify-playing-now-readme.akellbl4.vercel.app/api/auth
> - Put the url Redirect URI and click Add
> - Save changes with click to Save in end of the form
> - Open new tab on the browser and go to url which you put in Redirect URI. The url should looks like this https://spotify-playing-now-readme.akellbl4.vercel.app/api/auth

Try to go over these steps another time.
Final result should look like: `${your_domain}/api/auth` where `your_domain` is the domain where the app is hosted.

**Comment by barbarbar338** [comment]
Spotify dashboard: 

![dash](https://cdn.338.rocks/v1/storage/uploads/images/307952794759987200.png)

domain:

 ![domain](https://cdn.338.rocks/v1/storage/uploads/images/307953476904812545.png) (https://spotify-readme-badge.vercel.app/)

env variables: 

![variables](https://cdn.338.rocks/v1/storage/uploads/images/307953646346305538.png)

still same error

![error](https://cdn.338.rocks/v1/storage/uploads/images/307954144960970755.png)

**Comment by akellbl4** [comment]
I'll take a look today

**Comment by SaicharanKandukuri** [comment]
@akellbl4 @barbarbar338  I got the same error too
I followed this blog to get REFRESH TOKEN
> https://benwiz.com/blog/create-spotify-refresh-token/

**Comment by akellbl4** [comment]
@barbarbar338 you need to use deployment URL
![CleanShot 2022-06-09 at 10 27 46@2x](https://user-images.githubusercontent.com/2330682/172908509-273bc5f4-ab35-4d2f-aea5-f289bae3e3e6.png)

I'll fix readme

**Comment by barbarbar338** [comment]
Yeah that works, thanks!
