### ISSUE TITLE
Support for local files

### ISSUE THREAD

**Issue by IvanGodinez21** [akellbl4/spotify-badge#8]
### Issue description

Playing local files doesn't work, if is it possible, could you please add support for the local files?

There is no problem if the cover doesn't load (I remember that it is not possible because Spotify API doesn't support the images of covers of local files) 😋

### Screenshots

![image](https://user-images.githubusercontent.com/45635827/194774660-820f7464-d14c-4767-8dac-a5313467fdab.png)

![image](https://user-images.githubusercontent.com/45635827/194774678-1b5ad0fa-d087-4d75-b595-8699e211285f.png)

**Comment by akellbl4** [comment]
Hey @IvanGodinez21, sorry I missed the issue.
I'm relying on data that sent to me from Spotify if it doesn't send covers for a track I have no resource to pull it. The only thing that I can do is to add placeholder so widget shows something

**Comment by IvanGodinez21** [comment]
Yeah, covers for local files aren't supported for some reason.
Also, It can be replaced by a default cover or SVG if you wish, or just add placeholder as you said, it's opt to you.

Example of default cover:

![image](https://user-images.githubusercontent.com/45635827/212437968-35b6f563-fadd-4fe0-bb4c-44d9d1fbdd4e.png)

**Comment by FroggyRocky** [comment]
@akellbl4 is it still an issue ? I would like to help with this one, if it is.

**Comment by FroggyRocky** [comment]
@akellbl4 https://github.com/akellbl4/spotify-badge/pull/13 this is my pull request that solves the issue

**Comment by akellbl4** [comment]
Resolved #13
