### ISSUE TITLE
500: INTERNAL_SERVER_ERROR after push

### ISSUE THREAD

**Issue by sammyngy** [akellbl4/spotify-badge#9]
![image](https://user-images.githubusercontent.com/32553897/211925430-f8155330-01a2-495d-b02f-8acde1271538.png)

**Comment by sammyngy** [comment]
Hi kinda wierd, I've done all the setps

**Comment by akellbl4** [comment]
Hey @sammyngy, Could you please share logs from Vercel console. You need to open the project and click View Function logs and open the function. You should get the error that occurs, so I can debug from there

**Comment by sammyngy** [comment]
Hi, yup
![image](https://user-images.githubusercontent.com/32553897/212468149-eba56e95-b7eb-4aaf-bf4d-9fa5f7a0ba71.png)

**Comment by sammyngy** [comment]
Looks like a typescript issue, I've converted every file in .js and it work

**Comment by k-lin-k** [comment]
Could you share how exactly you solved this? I'm running into the same issue...

**Comment by sammyngy** [comment]
You have to build the project then it will generate js file, after that you delete all the .ts file and run the project 
I didn't find a better way to make this work :/

**Comment by akellbl4** [comment]
Not the best suggestion. Vercel used to handle ts files fine. I'll give it a look, maybe it needs to have update to their tooling.

**Comment by 0x0elliot** [comment]
same error.
